### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [connor-create/wsbtrades#4]

**Comment by DGKSK8LIFE** [comment]
Can you actually improve docs though? Like just a written explanation of your algorithm and usage of it? Ty

**Comment by connor-create** [comment]
I will write up a short usage and what this is meant for tomorrow but this
script is moreso meant as a joke so I don't want people to use it without
understanding that.

**Comment by DGKSK8LIFE** [comment]
Yeah makes sense. Ty. Loved the vid btw.
